In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('advertising.csv')

In [3]:
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country            Timestamp  Clicked on Ad  
0                   Tunisia  2016-03-27 00:53:11              0  
1                     Nauru  2016-04-04 01:39:02              0  
2                San Marino  2016-03-13 20:35:42              0  
3                     Italy  2016-01-10 02:31:19              0  
4                   Iceland  2016-06-03 03:36:18              0  
..                      ...                  ...            ...  
995                 Lebanon  2016-02-11 21:49:00              1  
996  Bosnia and Herzegovina  2016-04-22 02:07:01              1  
997                Mongolia  2016-02-01 17:24:57              1  
998               Guatemala  2016-03-24 02:35:54              0  
999                  Brazil  2016-06-03 21:43:21              1  

[1000 rows x 10 columns]

Trying to get more data out of the Timestamp(ie split into season and morning/evening)

In [4]:
def get_season(time):
    month = time[5:7]
    if int(month[0])==0:
        if int(month[1])<3:
            return 'Winter'
        elif int(month[1])<6:
            return 'Spring'
        elif int(month[1])<9:
            return 'Summer'
    else:
        if int(month) < 11:
            return 'Fall'
    return 'Winter'


In [5]:
temp = df['Timestamp'].apply(lambda x: get_season(x))

In [7]:
temp.value_counts()

Spring    450
Winter    307
Summer    243
Name: Timestamp, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
label = LabelEncoder()
new_temp = label.fit_transform(temp)

In [11]:
new_temp

array([0, 0, 0, 2, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 2, 0,
       0, 0, 1, 0, 2, 1, 0, 2, 1, 0, 1, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2,
       2, 2, 2, 1, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0,
       2, 1, 2, 0, 2, 1, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 1, 0,
       0, 0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 1, 1, 1, 1, 2, 1, 2, 1, 0, 0, 0,
       2, 1, 0, 2, 2, 1, 1, 1, 1, 1, 0, 0, 2, 2, 1, 0, 0, 0, 0, 1, 0, 1,
       2, 2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 0, 2, 2, 0, 1, 0, 2, 0, 0, 2,
       1, 0, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 1,
       2, 2, 0, 0, 2, 2, 0, 2, 1, 2, 0, 1, 2, 1, 2, 0, 1, 1, 2, 0, 1, 0,
       2, 2, 1, 2, 0, 0, 0, 2, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 0, 1, 2,
       1, 0, 0, 2, 0, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 2,
       1, 1, 1, 2, 0, 2, 2, 0, 1, 2, 0, 1, 2, 2, 2, 1, 0, 1, 0, 1, 2, 0,
       1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
df['Season Encoder'] = scaler.fit_transform(new_temp.reshape(-1,1))

In [20]:
df['Season Encoder']

0     -0.998572
1     -0.998572
2     -0.998572
3      1.331818
4      0.166623
         ...   
995    1.331818
996   -0.998572
997    1.331818
998   -0.998572
999    0.166623
Name: Season Encoder, Length: 1000, dtype: float64

In [21]:
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country            Timestamp  Clicked on Ad  \
0                   Tunisia  2016-03-27 00:53:11              0   
1                     Nauru  2016-04-04 01:39:02              0   
2                San Marino  2016-03-13 20:35:42              0   
3                     Italy  2016-01-10 02:31:19              0   
4                   Iceland  2016-06-03 03:36:18              0   
..                      ...                  ...            ...   
995                 Lebanon  2016-02-11 21:49:00              1   
996  Bosnia and Herzegovina  2016-04-22 02:07:01              1   
997                Mongolia  2016-02-01 17:24:57              1   
998               Guatemala  2016-03-24 02:35:54              0   
999                  Brazil  2016-06-03 21:43:21              1   

     Season Encoder  
0         -0.998572  
1         -0.998572  
2         -0.998572  
3          1.331818  
4          0.166623  
..              ...  
995        1.331818  
996       -0.998572  
997        1.331818  
998       -0.998572  
999        0.166623  

[1000 rows x 11 columns]

In [35]:
def get_morn_or_even(time):
    time = time[11:13]
    #print(time)
    if (time[0]) == 0:
        return "Morning"
    elif int(time)<12:
        return "Morning"
    else:
        return "Evening"

In [36]:
temp = df['Timestamp'].apply(lambda x: get_morn_or_even(x))

In [37]:
temp

0      Morning
1      Morning
2      Evening
3      Morning
4      Morning
        ...   
995    Evening
996    Morning
997    Evening
998    Morning
999    Evening
Name: Timestamp, Length: 1000, dtype: object

In [38]:
temp.value_counts()

Evening    503
Morning    497
Name: Timestamp, dtype: int64

In [39]:
label = LabelEncoder()

In [40]:
new_temp = label.fit_transform(temp)

In [41]:
new_temp

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,

In [42]:
scaler = StandardScaler()

In [43]:
df['Time Encoded'] = scaler.fit_transform(new_temp.reshape(-1,1))

In [44]:
df['Time Encoded']

0      1.006018
1      1.006018
2     -0.994018
3      1.006018
4      1.006018
         ...   
995   -0.994018
996    1.006018
997   -0.994018
998    1.006018
999   -0.994018
Name: Time Encoded, Length: 1000, dtype: float64

In [45]:
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country            Timestamp  Clicked on Ad  \
0                   Tunisia  2016-03-27 00:53:11              0   
1                     Nauru  2016-04-04 01:39:02              0   
2                San Marino  2016-03-13 20:35:42              0   
3                     Italy  2016-01-10 02:31:19              0   
4                   Iceland  2016-06-03 03:36:18              0   
..                      ...                  ...            ...   
995                 Lebanon  2016-02-11 21:49:00              1   
996  Bosnia and Herzegovina  2016-04-22 02:07:01              1   
997                Mongolia  2016-02-01 17:24:57              1   
998               Guatemala  2016-03-24 02:35:54              0   
999                  Brazil  2016-06-03 21:43:21              1   

     Season Encoder  Time Encoded  
0         -0.998572      1.006018  
1         -0.998572      1.006018  
2         -0.998572     -0.994018  
3          1.331818      1.006018  
4          0.166623      1.006018  
..              ...           ...  
995        1.331818     -0.994018  
996       -0.998572      1.006018  
997        1.331818     -0.994018  
998       -0.998572      1.006018  
999        0.166623     -0.994018  

[1000 rows x 12 columns]

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['Ad Topic Line','City','Country','Timestamp','Clicked on Ad'],axis = 1), df['Clicked on Ad'], test_size = .3)
logmodel = LogisticRegression()

In [50]:
logmodel.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [51]:
pred = logmodel.predict(X_test)

In [52]:
from sklearn.metrics import classification_report,confusion_matrix

In [53]:
print(classification_report(y_test, pred))
print("\n")
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.90      0.95      0.93       146
           1       0.95      0.90      0.93       154

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300



[[139   7]
 [ 15 139]]


In [54]:
from sklearn.ensemble import RandomForestClassifier

In [55]:
rfc = RandomForestClassifier(n_estimators=600)

In [56]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [57]:
pred = rfc.predict(X_test)

In [58]:
print(classification_report(y_test, pred))
print("\n")
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       146
           1       0.99      0.96      0.97       154

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



[[144   2]
 [  6 148]]


In [59]:
from sklearn.model_selection import GridSearchCV

In [60]:
param_grid = {
    'n_estimators': [100, 200, 300,500,600,800],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [62]:
rfc = RandomForestClassifier()
grid_search = GridSearchCV(estimator=rfc,param_grid=param_grid,cv=5, scoring='accuracy')

In [63]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [65]:
best_param = grid_search.best_params_

In [66]:
best_param

{'max_depth': None,
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'n_estimators': 500}

In [67]:
pred = grid_search.predict(X_test)
print(classification_report(y_test,pred))
print('\n')
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       146
           1       0.99      0.96      0.97       154

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



[[144   2]
 [  6 148]]


In [68]:
pip install xgboost

   --------------------------------------- 125.4/125.4 MB 16.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [69]:
import xgboost as xgb

In [70]:
clf = xgb.XGBClassifier()

In [71]:
clf.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='binary:logistic',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [72]:
pred = clf.predict(X_test)

In [73]:
print(classification_report(y_test,pred))
print('\n')
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.94      0.99      0.96       146
           1       0.99      0.94      0.96       154

    accuracy                           0.96       300
   macro avg       0.96      0.96      0.96       300
weighted avg       0.96      0.96      0.96       300



[[144   2]
 [  9 145]]


In [74]:
from sklearn.svm import SVC

In [79]:
clf = SVC(kernel='linear')

In [80]:
clf.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [81]:
pred = clf.predict(X_test)

In [82]:
print(classification_report(y_test,pred))
print('\n')
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       146
           1       1.00      0.96      0.98       154

    accuracy                           0.98       300
   macro avg       0.98      0.98      0.98       300
weighted avg       0.98      0.98      0.98       300



[[146   0]
 [  6 148]]


In [83]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['linear']} 

In [84]:
grid_search = GridSearchCV(estimator=SVC(),param_grid=param_grid,refit=True, verbose=3)

In [85]:
grid_search.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.943, total=   2.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.9s remaining:    0.0s


[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.979, total=   1.7s
[CV] C=0.1, gamma=1, kernel=linear ...................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.7s remaining:    0.0s


[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.979, total=   1.0s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.957, total=   1.4s
[CV] C=0.1, gamma=1, kernel=linear ...................................
[CV] ....... C=0.1, gamma=1, kernel=linear, score=0.957, total=   1.3s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.943, total=   2.0s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.979, total=   1.8s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.979, total=   1.0s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] ..... C=0.1, gamma=0.1, kernel=linear, score=0.957, total=   1.4s
[CV] C=0.1, gamma=0.1, kernel=linear .................................
[CV] .

[CV] ..... C=10, gamma=0.01, kernel=linear, score=0.943, total=   1.6s
[CV] C=10, gamma=0.01, kernel=linear .................................
[CV] ..... C=10, gamma=0.01, kernel=linear, score=0.964, total=   9.4s
[CV] C=10, gamma=0.01, kernel=linear .................................
[CV] ..... C=10, gamma=0.01, kernel=linear, score=0.979, total=   0.4s
[CV] C=10, gamma=0.01, kernel=linear .................................
[CV] ..... C=10, gamma=0.01, kernel=linear, score=0.957, total=   2.9s
[CV] C=10, gamma=0.01, kernel=linear .................................
[CV] ..... C=10, gamma=0.01, kernel=linear, score=0.943, total=   3.3s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] .... C=10, gamma=0.001, kernel=linear, score=0.943, total=   1.3s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] .... C=10, gamma=0.001, kernel=linear, score=0.964, total=  10.6s
[CV] C=10, gamma=0.001, kernel=linear ................................
[CV] .

[CV] .. C=1000, gamma=0.001, kernel=linear, score=0.957, total=   3.2s
[CV] C=1000, gamma=0.001, kernel=linear ..............................
[CV] .. C=1000, gamma=0.001, kernel=linear, score=0.964, total=   3.1s
[CV] C=1000, gamma=0.0001, kernel=linear .............................
[CV] . C=1000, gamma=0.0001, kernel=linear, score=0.943, total=   1.2s
[CV] C=1000, gamma=0.0001, kernel=linear .............................
[CV] . C=1000, gamma=0.0001, kernel=linear, score=0.986, total=   3.3s
[CV] C=1000, gamma=0.0001, kernel=linear .............................
[CV] . C=1000, gamma=0.0001, kernel=linear, score=0.979, total=   0.4s
[CV] C=1000, gamma=0.0001, kernel=linear .............................
[CV] . C=1000, gamma=0.0001, kernel=linear, score=0.957, total=   3.4s
[CV] C=1000, gamma=0.0001, kernel=linear .............................
[CV] . C=1000, gamma=0.0001, kernel=linear, score=0.964, total=   3.0s


[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:  5.1min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [86]:
best_params = grid_search.best_params_

In [87]:
best_params

{'C': 1000, 'gamma': 1, 'kernel': 'linear'}

In [88]:
pred = grid_search.predict(X_test)

In [89]:
print(classification_report(y_test,pred))
print('\n')
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       146
           1       0.99      0.98      0.98       154

    accuracy                           0.98       300
   macro avg       0.98      0.98      0.98       300
weighted avg       0.98      0.98      0.98       300



[[144   2]
 [  3 151]]
